customer/urls.py
from django.urls import path
from customer import views

urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("register", views.RegistrationView.as_view(), name="registration"),
    path("home", views.HomeView.as_view(), name="home"),
    path("products/<int:id>", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/<int:id>/cart/add", views.AddToCartView.as_view(), name="add_to_cart"),
    path("cart/all", views.MyCatrView.as_view(), name="mycart"),
    path("cart/remove/<int:id>", views.remove_from_cart, name="remove"),
    path("cart/place_order/<int:cid>/<int:pid>", views.PlaceOrderView.as_view(), name="place_order"),
]

futurestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework.routers import DefaultRouter
# from storeapi import views
#
# router = DefaultRouter()
# router.register('api/v1/registration', views.UserRegistrationView, basename="register")
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("customer.urls")),
                  path("dashboard/", include("owner.urls")),
                  path("api/", include("storeapi.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner/urls.py
from django.urls import path
from owner import views

urlpatterns = [
  path("admin-dashboard",views.AdminDashboardView.as_view(),name="dashboard"),
  path("orders/latest",views.OrdersListView.as_view(),name="orders_list"),
  path("orders/latest/detail/<int:id>",views.OrderDetailView.as_view(),name="order_detail"),

]

owner/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.


class Categorys(models.Model):
    category_name = models.CharField(max_length=200, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.category_name


class Products(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    category = models.ForeignKey(Categorys, on_delete=models.CASCADE)
    image = models.ImageField()
    price = models.PositiveIntegerField()
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.product_name


class Cart(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    options = (
        ("in-cart", "in-cart"),
        ("order-placed", "ordered-placed"),
        ("canceled", "canceled")
    )
    status = models.CharField(max_length=12, choices=options, default="in-cart")
    qty = models.PositiveIntegerField()


class Reviews(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    rating = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(5)])


class Orders(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True, null=True)
    delivery_address = models.CharField(max_length=200, null=True)
    expected_delivery_date = models.DateTimeField(null=True)
    options = (
        ("order-placed", "order-placed"),
        ("dispatched", "dispatched"),
        ("in-transit", "in-transit"),
        ("delivered", "delivered")
    )
    status = models.CharField(max_length=12, choices=options, default="order-placed")

customer/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = [
            "username", "email", "password1", "password2"
        ]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"})
        }


class CartForm(forms.Form):
    qty = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}))


class OrderFrom(forms.Form):
    delivery_address = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))

customer/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, CreateView, TemplateView, FormView, DetailView, ListView
from customer import forms
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from owner import models
from django.contrib import messages
from customer.decorators import signin_required
from django.utils.decorators import method_decorator


# Create your views here.

class RegistrationView(CreateView):
    form_class = forms.RegistrationForm
    template_name = "registration.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        messages.success(self.request, "your account has been created")
        return super().form_valid(form)


class LoginView(FormView):
    template_name = "login.html"
    form_class = forms.LoginForm

    def post(self, request, *args, **kwargs):
        form = forms.LoginForm(request.POST, files=request.FILES)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if request.user.is_superuser:
                    return redirect("dashboard")
                else:
                    return redirect("home")
            else:
                messages.error(request, "login failed!"
                                        " invalid username or password")
                return render(request, "login.html", {"form": form})


@method_decorator(signin_required, name="dispatch")
class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = models.Products.objects.all()
        return context


@method_decorator(signin_required, name="dispatch")
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect("login")


@method_decorator(signin_required, name="dispatch")
class ProductDetailView(DetailView):
    template_name = "product_detail.html"
    model = models.Products
    context_object_name = "product"
    pk_url_kwarg = "id"


@method_decorator(signin_required, name="dispatch")
class AddToCartView(FormView):
    template_name = "add_to_cart.html"
    form_class = forms.CartForm

    def get(self, request, *args, **kwargs):
        id = kwargs.get("id")
        product = models.Products.objects.get(id=id)

        return render(request, self.template_name, {"form": forms.CartForm(), "product": product})

    def post(self, request, *args, **kwargs):
        id = kwargs.get("id")
        product = models.Products.objects.get(id=id)
        qty = request.POST.get("qty")
        user = request.user
        models.Cart.objects.create(product=product, user=user, qty=qty)
        messages.success(request, "item added to cart")
        return redirect("home")


@method_decorator(signin_required, name="dispatch")
class MyCatrView(ListView):
    model = models.Cart
    template_name = "cart_list.html"
    context_object_name = "carts"

    def get_queryset(self):
        return models.Cart.objects.filter(user=self.request.user).exclude(status="canceled").order_by("-created_date")


@signin_required
def remove_from_cart(request, *args, **kwargs):
    cart_id = kwargs.get("id")
    cart_prod = models.Cart.objects.get(id=cart_id)
    cart_prod.status = "canceled"
    cart_prod.save()
    messages.success(request, "REMOVED")
    return redirect("mycart")


@method_decorator(signin_required, name="dispatch")
class PlaceOrderView(FormView):
    template_name = "place_order.html"
    form_class = forms.OrderFrom

    def post(self, request, *args, **kwargs):
        cart_id = kwargs.get("cid")
        product_id = kwargs.get("pid")
        cart = models.Cart.objects.get(id=cart_id)
        product = models.Products.objects.get(id=product_id)
        user = request.user
        delivery_address = request.POST.get("delivery_address")
        models.Orders.objects.create(product=product, user=user, delivery_address=delivery_address)
        cart.status = "order-placed"
        cart.save()
        messages.success(request, "order placed")
        return redirect("home")

customer/templates/add_to_cart.html
{%extends 'base.html'%}
{%block body_block%}

<div class="container-fluid">
    <div class="row ">
        <div class="col-4"></div>
        <div class="col-4">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{product.image.url}}" alt="..."/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{product.product_name}}</h5>
                        <!-- Product price-->
                        ${{product.price}}
                        <p>{{product.description}}</p>
                        <p>{{product.category}}</p>
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <!--                    <div class="text-center"><a class="btn btn-outline-dark mt-auto"-->
                    <!--                                                href="{%url 'add_to_cart' product.id%}">Add to cart</a></div>-->
                    <form action="" method="post">

                        {%csrf_token%}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-outline-dark mt-auto"> Add </button>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <div class="col-4"></div>

</div>
</div>

{%endblock%}

customer/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{%static 'css/styles.css'%}" rel="stylesheet"/>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Future Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'home'%}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                        <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                    </ul>
                     <li class="nav-item"><a class="nav-link" href="#!">Logout</a></li>
                </li>
            </ul>
            <form class="d-flex">
                <a href="{%url 'mycart'%}" class ="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{request.user.cart_set.all.count}}</span>
                </a>
            </form>
        </div>
    </div>
</nav>
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shop in style</h1>
            <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
{%block body_block%}

    {%endblock%}
</section>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{%static 'js/scripts.js'%}"></script>
</body>
</html>

customer/templates/cart_list.html
{%extends 'base.html'%}
{%block body_block%}

<div class="container-fluid">
    <div class="row gx•4 gx-lg•5 row-cots-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {%for cart in carts%}
        <div class="col-2"></div>
        <div class="col-6 mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{cart.product.image.url}}" alt="..."/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{cart.product.product_name}}</h5>
                        <!-- Product price-->
                        ${{cart.product.price}}
                    </div>
                </div>

            </div>
        </div>
        <div class="col-2">
            <p> qty:{{cart.qty}}
            </p>
            <p> status:{{cart.status}}
            </p>
        </div>
        <div class="col-2">
            <a href="{%url 'remove' cart.id%}" class="btn btn-outline-danger">cancel</a>

            {%if cart.status != "order-placed"%}
            <a href="{%url 'place_order' cart.id cart.product.id%}" class="btn btn-outline-success">Checkout</a>


            {%endif%}
        </div>
        {%endfor%}
    </div>
</div>

{%endblock%}

customer/templates/home.html
{%extends 'base.html'%}
{%block body_block%}

<div class="container-fluid">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {% if messages %}
            {% for msg in messages %}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{msg}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
             {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{msg}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}

            {% endfor %}

            {%endif%}
        </div>
    <div class="row gx•4 gx-lg•5 row-cots-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {%for product in products%}

        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{product.image.url}}" alt="..."/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{product.product_name}}</h5>
                        <!-- Product price-->
                       ₹{{product.price}}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{%url 'product_detail' product.id%}">View options</a></div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>

{%endblock%}

customer/templates/login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {% if messages %}
            {% for msg in messages %}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{msg}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{msg}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}

            {% endfor %}

            {%endif%}
        </div>

        <div class="row mt-5">

            <div class="col-3"></div>

            <div class="col-6 border">
                <h2>Login</h2>
                <form action="" class="mt-5" method="post">
                    {%csrf_token%}
                    {{form.as_p}}

                    <div class="mb-3">
                        <button type="submit" class="btn btn-info">login</button>
                    </div>

                </form>
                <a href="{%url 'registration'%}"> new! register here</a>
            </div>

            <div class="col-3"></div>
        </div>
    </div>


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</html>

customer/templates/place_order.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>
<body>
<div class="container">

    <div class="row mt-5">

        <div class="col-3"></div>

        <div class="col-6 border">
            <h2>Place order</h2>
            <form action="" class="mt-5" method="post">
                {%csrf_token%}
                {{form.as_p}}

                <div class="mb-3">
                    <button type="submit" class="btn btn-info">Order</button>
                </div>

            </form>
        </div>

        <div class="col-3"></div>
    </div>
</div>


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</html>

customer/templates/product_detail.html
{%extends 'base.html'%}
{%block body_block%}

<div class="container-fluid">
    <div class="row gx•4 gx-lg•5 row-cots-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        <div class="col-4"></div>
        <div class="col-4">

            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{product.image.url}}" alt="..."/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{product.product_name}}</h5>
                        <!-- Product price-->
                        ${{product.price}}
                        <p>{{product.description}}</p>
                        <p>{{product.category}}</p>
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                href="{%url 'add_to_cart' product.id%}">Add to cart</a></div>
                </div>
            </div>
        </div>
        <div class="col-4"></div>

    </div>
</div>

{%endblock%}

customer/templates/registration.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>
<body>
<div class="container">

    <div class="row mt-5">

        <div class="col-3"></div>

        <div class="col-6 border">
            <h2>register</h2>
            <form action="" class="mt-5" method="post">
                {%csrf_token%}
                {{form.as_p}}

                <div class="mb-3">
                    <button type="submit" class="btn btn-info">login</button>
                </div>

            </form>
        </div>

        <div class="col-3"></div>
    </div>
</div>


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</html>